### ISSUE TITLE
nidaqmx doesn't work on Python 2.7.13

### ISSUE THREAD

**Issue by brianlee1200** [ni/nidaqmx-python#1]
There is an [issue](http://bugs.python.org/issue29082) in Python 2.7.13 where _ctypes.LoadLibrary no longer accepts Unicode objects. This will be patched in 2.7.14, but for now users should downgrade to 2.7.12 to use the **nidaqmx** package.

**Comment by epage** [comment]
Its [mid-2017](https://www.python.org/dev/peps/pep-0373/) and I'm not seeing much chatter about Python 2.7.14.

For nixnet we had the following problems
- Like nidaqmx, 2.7.13's `ctypes` didn't accept unicode (https://github.com/ni/nixnet-python/issues/127)
- 2.7.7 is the first release where the `struct` module supported unicode (https://github.com/ni/nixnet-python/issues/116)

We found that just removing `unicode_literals` was sufficient to get nixnet working in all 2.7 versions without any downsides.

See https://github.com/ni/nixnet-python/pull/129
