### ISSUE TITLE
General Query CDAQ-9189

### ISSUE THREAD

**Issue by e0003315** [ni/nidaqmx-python#103]
Hi, I am a student and new to this. My project is currently using a CDAQ-9189 with multiple sensors connected to it. For my application, I am trying to do a simple task of retrieve data from this DAQ via the ethernet port from an RPI or a Tx2 which has a Ubuntu OS. Does this library only support Windows? Any other solutions that you can provide me with?

**Comment by zhindes** [comment]
This is a general NI-DAQmx problem and not an issue with the `nidaqmx` Python bindings. Consider posting on https://forums.ni.com/ for help resolving issues such as this.
