### ISSUE TITLE
Problem for Select Output type drive

### ISSUE THREAD

**Issue by MathiasR19** [ni/nidaqmx-python#112]
Hi all, 
I want to configure output per output of my IO card. for example I want output p1.0 to be active drive and p1.1 to be open collector. I can’t figure out how to do that in python.
I can made it with Labview.
I found this on internet :
https://nidaqmx-python.readthedocs.io/en/latest/do_channel.html#nidaqmx._task_modules.channels.do_channel.DOChannel
or 
https://nidaqmx-python.readthedocs.io/en/latest/constants.html

I tried a lot of possibilities but i can't do it.
This is my software and my tests in comment : 

Active_Drive = 12573
Open_collector = 12574

import nidaqmx

### Détecte les devices reconnues ####
system = nidaqmx.system.System.local()
for device in system.devices:
    devices = str(device)
    print (devices)
    print()

task = nidaqmx.Task()
# nidaqmx.constants.DigitalDriveType(Active_Drive)
task.do_channels.add_do_chan("CarteIO/port0/line0")

# nidaqmx.DOChannel.do_output_drive_type("CarteIO/port0/line0",Active_Drive)
#nidaqmx.channel.do.output_drive_type("CarteIO/port0/line0",Active_Drive)
# nidaqmx.task.DOChannel(Actvie_Drain)

nidaqmx._task_modules.channels.channel.DOChannel.do_output_drive_type(Active_Drive)
task.start()
value1 = False
print('Valeur de la sortie :', value1)
task.write(value1)
task.stop
task.close()

If you know, how to do this, and il you can help me, that would be great. I think there are many people like me.

Thanks, 
Have a good day

**Comment by zhindes** [comment]
This is a general NI-DAQmx problem and not an issue with the `nidaqmx` Python bindings. Consider posting on https://forums.ni.com/ for help resolving issues such as this.
