### ISSUE TITLE
Issue in Frequency Measurement

### ISSUE THREAD

**Issue by gowthambavireddy** [ni/nidaqmx-python#118]
import nidaqmx
import pprint
from nidaqmx.constants import CounterFrequencyMethod

pp = pprint.PrettyPrinter(indent=4)

with nidaqmx.Task() as task:
    task.ci_channels.add_ci_freq_chan("Dev1/ctr1",
                                      meas_method=CounterFrequencyMethod.HIGH_FREQUENCY_2_COUNTERS)
    data = task.read()
    print(data)

    # print('1 Channel N Samples Read: ')
    data = task.read(number_of_samples_per_channel=8)
    print(data)
    # avg_data = sum(data) / len(data)
    # pp.pprint(avg_data)

I am trying to measure the frequency of 27Mhz with measurement method CounterFrequencyMethod.HIGH_FREQUENCY_2_COUNTERS method but I am getting zero. 

Any one please help me how measure the frequency with CounterFrequencyMethod.HIGH_FREQUENCY_2_COUNTERS

**Comment by zhindes** [comment]
This is a general NI-DAQmx problem and not an issue with the `nidaqmx` Python bindings. Consider posting on https://forums.ni.com/ for help resolving issues such as this.
