### ISSUE TITLE
Determining the analog input channels

### ISSUE THREAD

**Issue by umair3456** [ni/nidaqmx-python#125]
Sir i want to determnine all the analoge input channels connected with the NI_MAX in python..i have tried many ways..is there any way i can determine which card is analog input card and which one is digital input card? and also how can i identify the differance between input card and output card?.. 
i have try with folowwing code...
import nidaqmx.system
from nidaqmx.constants import TerminalConfiguration
from nidaqmx.system import Device

system=nidaqmx.system.System.local()
for devicer in system.devices:
   print(devicer)

Device(name="dev1")
Device(name="dev2")
Device(name="mydev")
import collections
print(isinstance(system.devices,collections.Sequence))
device=system.devices["mydev"]
device == nidaqmx.system.Device("mydev")
print(isinstance(device.ai_physical_chans, collections.Sequence))

phy_chan=device.ai_physical_chans['ai0']
print(phy_chan)
phy_chan=nidaqmx.system.PhysicalChannel("mydev/ai0")

**Comment by zhindes** [comment]
This is a general NI-DAQmx problem and not an issue with the `nidaqmx` Python bindings. Consider posting on https://forums.ni.com/ for help resolving issues such as this.
