### ISSUE TITLE
Multiple tasks writing to same tdms file

### ISSUE THREAD

**Issue by pkramersx** [ni/nidaqmx-python#141]
Trying to use multiple cdaqs with different sample rates.  Currently creating an individual task for each cdaq so they can have independent sample rates.  Library currently prevents writing to the same tdms file from multiple tasks.  If there's a way to do different sample rates for channels of the same task I'm open to that as well.

**Comment by zhindes** [comment]
This is a feature request of the NI-DAQmx driver and not an issue with the the `nidaqmx` Python bindings. Consider posting on https://forums.ni.com/ for help resolving issues such as this.
