### ISSUE TITLE
Integrate static analysis CI

### ISSUE THREAD

**Issue by epage** [ni/nidaqmx-python#19]
`nixnet` runs static analysis for every PR.

See
- https://github.com/ni/nixnet-python/blob/master/tox.ini
- https://github.com/ni/nixnet-python/blob/master/.travis.yml

Other potential tools (taken from https://github.com/mre/awesome-static-analysis/blob/master/README.md#python )
- bugbear
- pyroma
- Vulture
- Bandit

**Comment by bkeryan** [comment]
The PR build runs ni-python-styleguide, which uses flake8, pycodestyle, and black:
https://github.com/ni/nidaqmx-python/blob/master/.github/workflows/build.yml
