### ISSUE TITLE
AO speed 

### ISSUE THREAD

**Issue by Depth2World** [ni/nidaqmx-python#195]
Hi there,
 
The device is NI-DAQ 6343(BNC).

My work needs to switch the output voltage quickly. 
Can I adjust the speed of the analog output switch ？

Looking forward to your reply!
Ths.

**Comment by zhindes** [comment]
This question is a general NI-DAQ question that isn't relevant to the Python bindings. Feel free to post your questions on the [ni.com forums](https://forums.ni.com/t5/Discussion-Forums/ct-p/discussion-forums).
