### ISSUE TITLE
Attempting to switch the reference clock fails. 

### ISSUE THREAD

**Issue by okz** [ni/nidaqmx-python#203]
With  nidaqmx 0.6.5, PXI-5421

Trying to syncronise multiple device outputs, I tried using the simplest most obvious method : Reference Clock synchronization 

The PXI 5421 data sheet suggests this is possible: 

![image](https://user-images.githubusercontent.com/3274852/214555240-4aa7480c-5b13-46c5-9a77-a7093f6b726b.png)

However I get the following error, which given that the HW datasheet suggests it's available, and the task configured as an analogue output, I am not sure is correct: 
```
              nidaqmx.errors.DaqError: Specified property is not supported by the device or is not applicable to the task.
              Property: DAQmx_RefClk_Rate
```
              
Simplest code I assumed should have been OK below: 

```
    import pprint
    import nidaqmx
    from nidaqmx.constants import AcquisitionType, TaskMode

    pp = pprint.PrettyPrinter(indent=4)

    with nidaqmx.Task() as task:
        task.ao_channels.add_ao_voltage_chan(f'{DAQ_RESOURCE}/ao0')

        task.timing.ref_clk_src = "PXI_CLK10"

        task.timing.cfg_samp_clk_timing(1000)

        print('1 Channel 1 Sample Write: ')
        print(task.write(1.0))
        task.stop()
```

Kind regards,

**Comment by zhindes** [comment]
This GitHub is specific to the Python language bindings for DAQmx. The error you're seeing isn't specific to the Python wrappers, and is instead a behavior of the hardware-specific support. 

That being said, I can give you a bit of guidance. The 5421 is an Arbitrary Waveform Generator that happens to be supported by DAQmx, but is probably best supported by [nifgen](https://pypi.org/project/nifgen/) - documentation [here](https://nimi-python.readthedocs.io/en/master/nifgen.html). There are a few [examples on github](https://github.com/ni/nimi-python/tree/master/src/nifgen/examples), but I'm not sure if any are relevant to what you want to do. The [Signal Generators Forum on ni.com](https://forums.ni.com/t5/Signal-Generators/bd-p/310) is a better place to get feedback on developing applications with NI hardware.
