### ISSUE TITLE
Cannot set ADC sample timing

### ISSUE THREAD

**Issue by kpotier16** [ni/nidaqmx-python#204]
Hello, upon trying to read 16 thermocouple channels with a NI 9213 on a cDAQ-9174, I found that the sample acquisition time was very long. After some searching, I ran into this forum post and tried the recommended resolution:
https://forums.ni.com/t5/Multifunction-DAQ/Python-NI-DAQmx-API-ADCTimingMode/td-p/4016502
Can this fix be formally added?

**Comment by zhindes** [comment]
It is available on the ai_channel objects as defined [here](https://github.com/ni/nidaqmx-python/blob/master/nidaqmx/_task_modules/channels/ai_channel.py#L680).

```python
with nidaqmx.Task() as task:
   ai_channel = task.ai_channels.add_ai_voltage_chan("cDAQ1Mod3/ai0")
   ai_channel.ai_adc_timing_mode = ADCTimingMode.HIGH_SPEED
   ...
```
