### ISSUE TITLE
How to ensure no dropped samples with stream_readers.AnalogMultiChannelReader

### ISSUE THREAD

**Issue by ggggggggg** [ni/nidaqmx-python#207]
I'm using `nidaqmx.stream_readers.AnalogMultiChannelReader` and calling 

```python
import numpy as np
import nidaqmx as ni
import nidaqmx
import nidaqmx.stream_readers
import nidaqmx.stream_writers
from nidaqmx.constants import TaskMode
import nidaqmx.constants


def main():
    N_samp_per_read=1000 # be careful, too big will crash dastard!! pretty sure the udp packet has to be 8k or less
    N_chan = 4
    payload = np.zeros((N_samp_per_read,N_chan),dtype='int16')
    read_data = np.zeros((N_chan,N_samp_per_read),dtype='float64')
    sample_rate_hz = 100000

    with ni.Task() as read_task:
        for i in range(N_chan):
            read_task.ai_channels.add_ai_voltage_chan(f'Dev1/ai{i}')
        read_task.timing.cfg_samp_clk_timing(rate=sample_rate_hz, source="OnboardClock", 
        sample_mode=nidaqmx.constants.AcquisitionType.CONTINUOUS)
        reader =  ni.stream_readers.AnalogMultiChannelReader(read_task.in_stream)
        
        read_task.start()

        while True:
            reader.read_many_sample(read_data, number_of_samples_per_channel=N_samp_per_read)
            use_data(read_data) # do something specific with the data, typically send it over a tcp socket to another program
```

I'm suspicious that sometimes this code drops a sample between two reads. Eg read 1 starts at sample 0, read 2 should start at sample 1000, but actually starts at sample 1001. How can I check if I've missed a sample?

**Comment by zhindes** [comment]
The way DAQmx behaves, it guarantees you don't miss samples the way you've written your application. See [Continuous Acquisition and Generation with Finite Buffer Size](https://www.ni.com/docs/en-US/bundle/ni-daqmx/page/mxcncpts/contcacqgen.html) and [Controlling Where in the Buffer to Read Samples](https://www.ni.com/docs/en-US/bundle/ni-daqmx/page/mxcncpts/controlwherebufferread.html). If you miss data, DAQmx will give you an error.
