### ISSUE TITLE
empty list when we try to get device names (ubuntu 20.04)

### ISSUE THREAD

**Issue by csanrod** [ni/nidaqmx-python#218]
We tried using nidaqmx library by using python3 with NI-USB 6003 but we get an empty list. Our system and drivers info are:

- Ubuntu 20.04 LTS 
- NILinux2023Q1DeviceDrivers (stream version)
- ni-daqmx (apt install) 
- NI-USB 6003
- nidaqmx (pip3 install)

We need to obtain devices names to assign physicalname channels like "Dev0/ai1:4". Here is what we obtain:

![imagen](https://user-images.githubusercontent.com/48911749/223427315-7386fb93-5eef-478b-b49c-efd1e325226e.png)

And here we can see that the device is detected:
![imagen](https://user-images.githubusercontent.com/48911749/223427452-f45f6683-ec87-4458-b1b1-c912d53b11a4.png)

Thanks for your help, best regards.

**Comment by zhindes** [comment]
Unfortunately, the USB-6003 isn't supported on Linux. You can look up support for any given device on [NI Hardware and Software Operating System Compatibility (ni.com)](https://www.ni.com/en-us/support/documentation/compatibility/21/ni-hardware-and-operating-system-compatibility.html). That site is sort of hard to use, I apologize. Here is what it currently says.

![image](https://user-images.githubusercontent.com/42776655/223532913-b85fe45e-542e-4345-9cf3-1bbe67ca9a1a.png)

A quick and easy way to find out if NI-DAQmx knows about your device is to run `nilsdev` on the command line. That should list all the devices that have been discovered, and it uses the same mechanism that the Python bindings use.

**Comment by csanrod** [comment]
Oh ok, thanks for the information!
