### ISSUE TITLE
Using nidaqmx over ethernet

### ISSUE THREAD

**Issue by episodeyang** [ni/nidaqmx-python#28]
Hi,

Our lab is trying to use `nidaqmx` for a NI 9182 compactDAQmx chasis over the ethernet. 

The tutorials you have so far all concern a device mounted over USB. What would be the syntax to use for ethernet?

Here is what I have so far: It would be nice if there is a way to list devices, like the `visa` library.

```python
__author__ = 'Ge Yang'

ip_address = "192.168.1.216"
import nidaqmx
from nidaqmx.types import CtrTime
with nidaqmx.Task() as task:
    task.co_channels.add_co_pulse_chan_time("{ip}/ctr0".format(ip=ip_address))
    sample = CtrTime(high_time=0.001, low_time=0.001)
    task.write(sample)

with nidaqmx.Task() as task:
    task.ao_channels.add_ao_voltage_chan("{ip}/ao0".format(ip=ip_address))
    task.write([1.1, 2.2, 3.3, 4.4, 5.5], auto_start=True)
```

**Comment by Delta39** [comment]
Was there any solution for this?
