### ISSUE TITLE
Refresh examples to show real world code

### ISSUE THREAD

**Issue by epage** [ni/nidaqmx-python#31]
Currently, the examples feel like they focus on [highlighting parts of the API](https://github.com/ni/nidaqmx-python/blob/master/nidaqmx_examples/ci_count_edges.py) rather than showing best practices for using the API to accomplish a task.

**Comment by epage** [comment]
The LabVIEW examples were refreshed several years ago and could provide a good template of what they could be like.  While I've not looked at them, I'm assuming the LabVIEW NXG examples might be even better.

**Comment by zhindes** [comment]
We accept contributions for stuff like this. We may also prioritize this in the future for specific investments, but no need to track this independently.
