### ISSUE TITLE
Incorrect types in samp_quant_samp_per_chan and total_samp_per_chan_generated parameters

### ISSUE THREAD

**Issue by cthomas97** [ni/nidaqmx-python#32]
Both samp_quant_samp_per_chan  and total_samp_per_chan_generated parameters
use c_double types, rather than c_long_long (UInt64) as required by the dll function.
Changing line 949 and 957 in out_stream.py and 2230, 2238 and 2253 in timing.py restores correct operation.

**Comment by epage** [comment]
Thanks for using nidaqmx and thank you for letting us know of this problem!

For others sake, these are the related lines from NIDAQmx.h
```c
int32 __CFUNC DAQmxGetSampQuantSampPerChan(TaskHandle taskHandle, uInt64 *data);
int32 __CFUNC DAQmxGetWriteTotalSampPerChanGenerated(TaskHandle taskHandle, uInt64 *data);
```
