### ISSUE TITLE
latest NI-DAQmx Python API documentation is empty

### ISSUE THREAD

**Issue by matthias-tischler-ni** [ni/nidaqmx-python#341]
when going to https://nidaqmx-python.readthedocs.io/, you are automatically forwarded to https://nidaqmx-python.readthedocs.io/en/latest/

the individual pages like https://nidaqmx-python.readthedocs.io/en/latest/physical_channel.html are empty

nevertheless, the stable one is showing content, e.g. https://nidaqmx-python.readthedocs.io/en/stable/physical_channel.html

**Comment by zhindes** [comment]
FYI @bkeryan - mainline documentation isn't working quite right. The latest release (0.7.0) is fine. [CONTRIBUTING.md](https://github.com/ni/nidaqmx-python/blob/master/CONTRIBUTING.md) details how to built it locally to check into it.

**Comment by bkeryan** [comment]
I'll look into it. I wouldn't be surprised if https://github.com/ni/nidaqmx-python/pull/338 fixes it. It seems like we should add a doc generation check to tox.ini and possibly the PR build.

**Comment by bkeryan** [comment]
https://nidaqmx-python.readthedocs.io/en/latest/physical_channel.html has the correct content now.
