### ISSUE TITLE
no version information available

### ISSUE THREAD

**Issue by dolhop** [ni/nidaqmx-python#36]
There used to be a version.py file in nidaqmx, which seems to have been removed.  This was useful in that I could check nidaqmx.version and ensure that the minimum revision was installed for my application. 

Or, please provide a nidaqmx.__version__ like most python packages do.

The fact that older versions had a version.py file means that upgrading will leave the old file there, thus confusing the situation.

**Comment by epage** [comment]
Are you looking for the python package version or the driver version?

(I'm assuming package version but wanting to confirm)

**Comment by dolhop** [comment]
Yes, python package version.  I see the ability to detect the driver
versions.

Thanks.
