### ISSUE TITLE
Documentation does not include references for add_.*_channel functions

### ISSUE THREAD

**Issue by epage** [ni/nidaqmx-python#4]
See https://nidaqmx-python.readthedocs.io/en/latest/ai_channel.html

**Comment by brianlee1200** [comment]
Hey Ed,

I'm not quite sure what you mean. The documentation for the AI add_channel methods reside here:
https://nidaqmx-python.readthedocs.io/en/latest/ai_channel_collection.html

Is that what you're referring to? Or is it something else?

Brian

**Comment by epage** [comment]
Close me

I was mixed up. I was looking on the channel and not the channel collection.
