### ISSUE TITLE
运行nidaqmx时报错

### ISSUE THREAD

**Issue by feelonsim** [ni/nidaqmx-python#422]
import时出现以下错误：
NotImplementedError: Location of niDAQmx library and include file unknown on win32 - if you find out, please let the PyDAQmx project know

**Comment by zhindes** [comment]
[PyDAQmx](https://github.com/clade/PyDAQmx) is a separate Python package. If you want to use this package, try `pip install nidaqmx`. For what its worth, your error sounds like you might not have the NI-DAQmx driver installed, which is required for both packages. You can find the installer [here](https://www.ni.com/en-us/support/downloads/drivers/download.ni-daq-mx.html).
