### ISSUE TITLE
 synchronous AO & DO

### ISSUE THREAD

**Issue by Depth2World** [ni/nidaqmx-python#443]
Hi，there,

This is my simple hw AO code.

```python
 task.timing.cfg_samp_clk_timing(rate=5000, # jump rate
                                 active_edge=Edge.RISING,
                                 sample_mode=AcquisitionType.FINITE,
                                 samps_per_chan=grid_points**2*1000)    # scan 10 times
 task.write(total_table, auto_start=False,timeout=nidaqmx.constants.WAIT_INFINITELY)
 task.start()
 task.wait_until_done(timeout=nidaqmx.constants.WAIT_INFINITELY)
```

Now. I want to add a DO.  
(Each time AO outputs an analog signal, DO also outputs a digital signal.)
How can I realize that?

Hope for your help.
BR

**Comment by zhindes** [comment]
It depends on what device you have. Assuming it is a more capable device, you can share a sample clock. On your DO task, set the [source parameter of cfg_samp_clk_timing](https://nidaqmx-python.readthedocs.io/en/latest/timing.html#nidaqmx._task_modules.timing.Timing.cfg_samp_clk_timing). You can query the terminal to use from the AO task with [samp_clk_term](https://nidaqmx-python.readthedocs.io/en/latest/timing.html#nidaqmx._task_modules.timing.Timing.samp_clk_term). However, some devices don't support this functionality, and some may not support that `samp_clk_term` property. I'd recommend the [Multifunction DAQ board on ni.com](https://forums.ni.com/t5/Multifunction-DAQ/bd-p/250) for future support.
