### ISSUE TITLE
Linux supported?

### ISSUE THREAD

**Issue by 5frank** [ni/nidaqmx-python#54]
The nidaqmx-python/README.rst says that "nidaqmx supports only the Windows operating system". However, loading of the C library in linux seem to be supported in nidaqmx-python/nidaqmx/_lib.py.

Even if Linux support is experimental or in-official, perhaps it could still be mentioned in the README?

**Comment by 5frank** [comment]
I understand, but if there is no mentioning of Linux support there will probably be no Linux related contributions/testing/fixes either... 
I discovered it by accident and was actually looking for alternatives that would work on Linux.

**Comment by neilvana** [comment]
That's fair.  I'll see about adding something to the README.
