### ISSUE TITLE
passing int as first parameter to add_ai_voltage_chan

### ISSUE THREAD

**Issue by 5frank** [ni/nidaqmx-python#56]
Passing a int as first paramter to `add_ai_voltage_chan` will hang the process indefinetly. Keyboard interrupt (CTRL+C) did not work so I have no traceback,  i.e. unclear where it is stuck. Note that passing an invalid string works as expected an raises a error.
example:
```
with nidaqmx.Task() as task:
        task.ai_channels.add_ai_voltage_chan(123, 
            terminal_config=nidaqmx.constants.TerminalConfiguration.DIFFERENTIAL) 
```

**Comment by neilvana** [comment]
The first argument to pass to the function should be a string.  See:
https://nidaqmx-python.readthedocs.io/en/latest/ai_channel_collection.html#nidaqmx._task_modules.ai_channel_collection.AIChannelCollection.add_ai_voltage_chan

We could add additional type checking before passing the argument to the lower level driver, although this would have a slight performance impact and to apply universally would be difficult and have opted not to do it.  We have also considered adding type hinting to the API which is available in Python 3 and would make this programming error more obvious, but have not yet had the time to add it.
