### ISSUE TITLE
NextWriteIsLast : where is it ?

### ISSUE THREAD

**Issue by MaxP92** [ni/nidaqmx-python#58]
`Next Write is Last` which should be in `task.out_stream` : I can't find it.

Yet other advanced functions like `Wait Mode` are here.

FYI the command is `DAQmxSetWriteNextWriteIsLast`

**Comment by zhindes** [comment]
This took a lot of spelunking, but I have discovered that this attribute was never supported by any DAQmx devices. The attribute obsoleted in the NI-DAQmx API in 15.5.
