### ISSUE TITLE
task.ci_channel.citc_reached seems malformed

### ISSUE THREAD

**Issue by epage** [ni/nidaqmx-python#6]
See https://nidaqmx-python.readthedocs.io/en/latest/ci_channel.html#nidaqmx._task_modules.channels.ci_channel.CIChannel.citc_reached

Should it be `ci_tc_reached`?  Should `tc` even be abbreviated.  Looking at DAQmx's C# API, it is [TerminalCountReached](http://zone.ni.com/reference/en-XX/help/370473H-01/mstudiowebhelp/html/2f5b0aeb/)

**Comment by brianlee1200** [comment]
Hey Ed,

Yes, this should've been ``ci_tc_reached``. I've corrected this.

We agreed we wouldn't 'fix' abbreviations or at least we would defer the fix until a later release, thus I've left it as  ``ci_tc_reached``.
