### ISSUE TITLE
Counter input : read methods on NIdaqmx version < 10

### ISSUE THREAD

**Issue by MaxP92** [ni/nidaqmx-python#60]
Hello,

Trying to use a `counter input` I noticed few things:

(1) the `stream_readers.CounterReader` Class can be wrongly used : for instance, by calling `read_many_sample_pulse_time` for a counter that does not measure pulse time. The help in readthedocs could be clearer about this ("use the method X only if the counter is X"), and the error messages as well. 

(2) for NIdaqmx version < 10 (like in my case) - and maybe other version of Nidaqmx - the functions `_read_counter_f_64_ex` and `_read_counter_u_32_ex` are NOT available. So the call to `read()` or to `CounterReader` should call `_read_counter_f_64` and `_read_counter_u_32` instead (by probing the driver version with 

> system = nidaqmx.system.System.local()
DriverVersion=system.driver_version
major_version = DriverVersion[0] # 9 in my case

eventually).
The function should also raise a `warning` to update the driver, optionally.

NIdaqmx version 9.2.3
Python 64 bits on Windows 7 x64

**Comment by zhindes** [comment]
The behavior of erroring if a function isn't supported by the underlying installed NI-DAQmx version is by design. Adding overhead to check every new function for support is not worth the effort.
