### ISSUE TITLE
'Analog Window Trigger condition type' C getter / setter / resetter can't be called because the function name is incorrect

### ISSUE THREAD

**Issue by dratinyy** [ni/nidaqmx-python#63]
[According to the NI-DAQmx C Reference](http://zone.ni.com/reference/en-XX/help/370471AK-01/mxcprop/attr1401/), functions to call when accessing the Analog Window Trigger condition are:
* `DAQmxGetAnlgWinStartTrigWhen`
* `DAQmxSetAnlgWinStartTrigWhen`
* `DAQmxResetAnlgWinStartTrigWhen`

as opposed to what can be found in `nidaqmx/_task_modules/triggering/start_trigger.py` (lines [1036](https://github.com/ni/nidaqmx-python/blob/master/nidaqmx/_task_modules/triggering/start_trigger.py#L1036), [1052](https://github.com/ni/nidaqmx-python/blob/master/nidaqmx/_task_modules/triggering/start_trigger.py#L1052), [1065](https://github.com/ni/nidaqmx-python/blob/master/nidaqmx/_task_modules/triggering/start_trigger.py#L1036)), which end with 'Start**TrigTrig**When'.

I'm not adding extra information such as Python version and such since this is more of a mistake rather than a bug. Also I can confirm updating the function names will have them work as intended.

**Comment by rares-pop** [comment]
Addressing this in #93.
