### ISSUE TITLE
nidaqmx-python and pynidaqmx projects use the same package name

### ISSUE THREAD

**Issue by pearu** [ni/nidaqmx-python#64]
Hi!

I am the author of _PyLibNIDAQmx - a Python wrapper to libnidaqmx library_:
  https://github.com/pearu/pylibnidaqmx/
that has existed since 2009.

It appears that both nidaqmx-python and pynidaqmx projects define the same package name for Python users: `nidaqmx`. This most probably will cause confusion among our users in case they install both packages.

I suggest that both projects acknowledge the other project in their README file and warn users that only one package at the time can be installed.

What do you think?

**Comment by neilvana** [comment]
Seems reasonable.  I'll look into adding something into the README.
