### ISSUE TITLE
Documentation search results return "SORRY This page does not yet exist" 

### ISSUE THREAD

**Issue by dolorsitatem** [ni/nidaqmx-python#69]
This appears to be the case for all entries.

For example,

[](https://nidaqmx-python.readthedocs.io/en/latest/index.html)
Search for: nidaqmx.constants.ACExcitWireMode
Results are found, the first one being for nidaqmx.constants.ACExcitWireMode
Clicking on that link sends you to the error page

**Comment by wireddown** [comment]
![search_miss](https://user-images.githubusercontent.com/8404598/49025644-f67f0f80-f150-11e8-8cdf-721d96d49b92.gif)

**Comment by KennethNielsen** [comment]
The issue seems to be that there is a ".rst" in injected in the URI that shouldn't be there, i.e. the links goes to something like `.....task.rst.html....` where they should go to `.....task.html....`

**Comment by KennethNielsen** [comment]
AS outlines e.g. in this issue (https://github.com/rtfd/readthedocs.org/issues/2708), this seems to be related to a bug in sphinx 1.5 and the work-around for now is to downgrade the version.

**Comment by KennethNielsen** [comment]
I just wanted to bump this. The docs are not easy to use with this issue and if the solutions for now is to lock the sphinx versions at a lower version it should be a relatively simple fix.

**Comment by zhindes** [comment]
This appears to be resolved with our latest update to dependencies.
