### ISSUE TITLE
generate defragged tdms files

### ISSUE THREAD

**Issue by baudoux** [ni/nidaqmx-python#74]
The .tdms files generated by the stream are heavy to open, probably because they are not defragged.
I generate the file with:
```
task.in_stream.configure_logging(file_path,
        nidaqmx.constants.LoggingMode.LOG_AND_READ,
        'myGroupName',
        nidaqmx.constants.LoggingOperation.OPEN_OR_CREATE)
```
Is it possible to generate defragged files?

**Comment by AndrewHeim** [comment]
I don't think this is out of the norm for any sort of TDMS log.  Defragging is typically done post-facto.  Alas - I don't know of a python call to do so.  Maybe you could call some LabVIEW code (built as an exe) from python to do it?

**Comment by zhindes** [comment]
This is a feature request of the DAQmx API and not of the `nidaqmx` Python bindings. Consider making a request on https://forums.ni.com/.
