### ISSUE TITLE
nidaqmx.errors.DaqError on co_pulse_time.py example

### ISSUE THREAD

**Issue by charterchap** [ni/nidaqmx-python#78]
When running nidaqmx-python/nidaqmx_examples/co_pulse_time.py with my PXIe-6363 I get a 
`nidaqmx.errors.DaqError: Specified operation did not complete, because the specified timeout expired.` on task.write(). if I comment out the first task.write() I get the same problem on the second. I do see the Pulse Terminal on high while it runs, but it isn't actually pulsing.

```python3 import nidaqmx
from nidaqmx.types import CtrTime


with nidaqmx.Task() as task:
    task.co_channels.add_co_pulse_chan_time("PXI1Slot2/ctr0")
    sample = CtrTime(high_time=0.0001, low_time=0.0002)

    # print('1 Channel 1 Sample Write: ')
    # print(task.write(sample))

    samples = []
    for i in range(1, 5):
        x = i/float(1000)
        samples.append(CtrTime(high_time=x, low_time=x))

    print('1 Channel N Samples Write: ')
    print(task.write(samples, auto_start=True))```

**Comment by miercat0424** [comment]
How did you solve this problem?
