### ISSUE TITLE
`port0/line1:3` returns 2 lines rather than 3.

### ISSUE THREAD

**Issue by epage** [ni/nidaqmx-python#8]
Not sure if its just the documentation or the actual code but for this code from the README.rst file
```python
>>> from nidaqmx.constants import LineGrouping
>>> with nidaqmx.Task() as task:
...     task.di_channels.add_di_chan(
...         "cDAQ2Mod4/port0/line1:3", line_grouping=LineGrouping.CHAN_PER_LINE)
...     task.read(number_of_samples_per_channel=2)
...
[[False, True], [True, True]]
```

The task should have 3 lines in it (port0/line1, port0/line2, port0/line3) because the range syntax is inclusive (`[1, 3]`) rather than exclusive (`[1, 3)`).

I confirmed this by reproducing the code in LabVIEW (1Samp rather than NSamp read though).   I got 3 lines of bools back.

**Comment by brianlee1200** [comment]
Thanks Ed. This is just an error in the documentation.
