### ISSUE TITLE
Tests don't run with pytest 4.0+

### ISSUE THREAD

**Issue by charterchap** [ni/nidaqmx-python#80]
For example see test_read_write.py:365
```python    
    fixture_dev = x_series_device()
    max_port_width = max([d.do_port_width for d in fixture_dev.do_ports])

    @pytest.mark.skipif(
        len([d.do_port_width <= 16 for d in x_series_device().do_ports]) < 2,
        reason='task.read() accepts max of 32 bits for digital uint reads.')
```
will give an error: `AttributeError: 'function' object has no attribute 'do_ports'`
See pytest docs: https://docs.pytest.org/en/latest/deprecations.html#calling-fixtures-directly

**Comment by zhindes** [comment]
We recently updated all dependencies to their latest version and resolved issues.
