### ISSUE TITLE
Load Data from TDMS

### ISSUE THREAD

**Issue by jemmasters** [ni/nidaqmx-python#89]
I was looking at the nidaqmx-python docs and I didn't se any option (or maybe I miss) for reading data from an already created TDMS. Does this mean that my best option is to use the excel plugin for TDMS or use the npTDMS python package?

**Comment by zhindes** [comment]
This is a feature request of the DAQmx API and not of the `nidaqmx` Python bindings. Consider making a request on https://forums.ni.com/.
