### ISSUE TITLE
Look into refactoring _lib imports - caching it 

### ISSUE THREAD

**Issue by rares-pop** [ni/nidaqmx-python#99]
The import in check_for_error seems to be a workaround to avoid a circular import of the _lib.

Look into caching it.

**Comment by bkeryan** [comment]
The global `check_for_error` function was deprecated in 0.8.0: https://github.com/ni/nidaqmx-python/blob/master/src/handwritten/errors.py#L183

It was moved to the LibraryInterpreter object, which doesn't do any lazy imports.
